/turf/open/floor/ex_act(severity)
	if(hull_floor)
		return ..()
	switch(severity)
		if(EXPLODE_WEAK to EXPLODE_LIGHT)
			if(prob(50))
				break_tile()
		if(EXPLODE_LIGHT to EXPLODE_HEAVY)
			if(prob(80))
				make_plating()
			else
				break_tile()
		if(EXPLODE_HEAVY to INFINITY)
			make_plating()
	return ..()
