#define SELECTABLE_SQUADS list(\
	RADIO_CHANNEL_ALPHA,\
	RADIO_CHANNEL_BRAVO,\
	RADIO_CHANNEL_CHARLIE,\
	RADIO_CHANNEL_DELTA,\
	RADIO_CHANNEL_FOREIGN,\
	"None"\
	)

#define SELECTABLE_SQUADS_SOM list(\
	RADIO_CHANNEL_ZULU,\
	RADIO_CHANNEL_YANKEE,\
	RADIO_CHANNEL_XRAY,\
	RADIO_CHANNEL_WHISKEY,\
	RADIO_CHANNEL_TANGO,\
	"None"\
	)
