/obj/item/cell/ex_act(severity)
	switch(severity)
		if(0 to EXPLODE_WEAK)
			if(prob(25))
				corrupt()
			if(prob(50))
				corrupt()
		if(EXPLODE_WEAK to EXPLODE_LIGHT)
			if(prob(25))
				qdel(src)
				return
			if(prob(25))
				corrupt()
		if(EXPLODE_LIGHT to EXPLODE_HEAVY)
			if(prob(50))
				qdel(src)
				return
		if(EXPLODE_HEAVY to INFINITY)
			qdel(src)
