/obj/machinery/disposal/ex_act(severity)
	switch(severity)
		if(0 to EXPLODE_LIGHT)
			if(prob(25))
				qdel(src)
		if(EXPLODE_LIGHT to EXPLODE_HEAVY)
			if(prob(60))
				qdel(src)
		if(EXPLODE_HEAVY to INFINITY)
			qdel(src)

/obj/structure/disposalpipe/ex_act(severity)
	switch(severity)
		if(0 to EXPLODE_LIGHT)
			take_damage(rand(0, 15), BRUTE, BOMB)
		if(EXPLODE_LIGHT to EXPLODE_HEAVY)
			take_damage(rand(5, 15), BRUTE, BOMB)
		if(EXPLODE_HEAVY to INFINITY)
			qdel(src)
