/obj/structure/bookcase/ex_act(severity)
	switch(severity)
		if(0 to EXPLODE_LIGHT)
			if(prob(50))
				for(var/obj/item/book/b in contents)
					b.forceMove(get_turf(src))
				qdel(src)
		if(EXPLODE_LIGHT to EXPLODE_HEAVY)
			for(var/obj/item/book/b in contents)
				if(prob(50))
					b.forceMove(get_turf(src))
				else
					qdel(b)
			qdel(src)
		if(EXPLODE_HEAVY to INFINITY)
			for(var/obj/item/book/b in contents)
				qdel(b)
			qdel(src)
