/obj/structure/flora/ex_act(severity)
	switch(severity)
		if(0 to EXPLODE_WEAK)
			if(prob(10))
				qdel(src)
		if(EXPLODE_WEAK to EXPLODE_LIGHT)
			if(prob(50))
				qdel(src)
		if(EXPLODE_LIGHT to EXPLODE_HEAVY)
			if(prob(70))
				qdel(src)
		if(EXPLODE_HEAVY to INFINITY)
			qdel(src)

/obj/structure/flora/tree/ex_act(severity)
	take_damage(severity, BRUTE, BOMB)
	START_PROCESSING(SSobj, src)
