/obj/structure/lamarr/ex_act(severity)
	switch(severity)
		if(EXPLODE_WEAK to EXPLODE_LIGHT)
			if(prob(50))
				take_damage(5, BRUTE, BOMB)
		if(EXPLODE_LIGHT to EXPLODE_HEAVY)
			if(prob(50))
				take_damage(15, BRUTE, BOMB)
		if(EXPLODE_HEAVY to INFINITY)
			deconstruct(FALSE)
