/obj/structure/reagent_dispensers/ex_act(severity)
	switch(severity)
		if(0 to EXPLODE_LIGHT)
			if(prob(5))
				new /obj/effect/particle_effect/water(loc)
				qdel(src)
		if(EXPLODE_LIGHT to EXPLODE_HEAVY)
			if(prob(50))
				new /obj/effect/particle_effect/water(loc)
				qdel(src)
		if(EXPLODE_HEAVY to INFINITY)
			qdel(src)
